plugins: fetchart embedart convert scrub replaygain lastgenre chroma web duplicates missing discogs
directory: /mnt/music/Library/Albums
library: /config/musiclibrary.blb
art_filename: albumart
threaded: yes
original_date: no
per_disc_numbering: no
# files/directories matching one of these patterns are ignored during import
ignore: [".*", "*~", "System Volume Information"]
# files matching these patterns are deleted from source after import
clutter: ["Thumbs.DB", ".DS_Store", "*.m3u", ".pls", "*.jpg"]

convert:
    auto: no
    ffmpeg: /usr/bin/ffmpeg
    opts: -ab 320k -ac 2 -ar 48000
    max_bitrate: 320
    threads: 1
    
paths:
    default: $albumartist/$original_year - $album%aunique{}/$track - $title
    singleton: Singles/$artist - $title
    comp: Compilations/$year - $album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 
        
import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: yes
    quiet_fallback: skip
    #incremental_skip_later: no
    none_rec_action: ask
    timid: no
    log: /config/beet.log

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes
    maxwidth: 300

fetchart:
    auto: yes
    maxwidth: 300
    cautious: true
    cover_names: cover folder

missing:
    format: $albumartist - $album - $track - $title
    count: no
    total: no

duplicates:
  checksum: no

replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\s+$': ''

web:
    host: 0.0.0.0
    port: 8337

